In [99]:
import matplotlib as mpl
import matplotlib.pyplot as plt

import numpy as np
import pandas as pd

In [100]:
churn = pd.read_csv(r'C:\\Users\\User\\Desktop\\python DBA proj 2022\\Python Data Analysis\\churn.csv')
churn.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [101]:
churn.shape

(7043, 21)

In [102]:
churn.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [103]:
churn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [104]:
churn=churn.drop(['customerID'], axis=1)
churn

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [128]:
churn.loc[churn.gender == 'Male', 'gender'] = 1
churn.loc[churn.gender == 'Female', 'gender'] = 0
churn = churn.astype({"gender": 'int64'}) 

churn.Partner = (churn.Partner=='Yes').astype('int')
churn.Dependents = (churn.Dependents=='Yes').astype('int')
churn.PhoneService = (churn.PhoneService=='Yes').astype('int')
churn.MultipleLines = (churn.MultipleLines=='Yes').astype('int')
churn.OnlineSecurity = (churn.OnlineSecurity=='Yes').astype('int')
churn.OnlineBackup = (churn.OnlineBackup=='Yes').astype('int')
churn.DeviceProtection = (churn.DeviceProtection=='Yes').astype('int')
churn.TechSupport = (churn.TechSupport=='Yes').astype('int')
churn.StreamingTV = (churn.StreamingTV=='Yes').astype('int')
churn.StreamingMovies = (churn.StreamingMovies=='Yes').astype('int')
churn.PaperlessBilling = (churn.PaperlessBilling=='Yes').astype('int')
churn.Churn = (churn.Churn=='Yes').astype('int')

churn['TotalCharges'] = pd.to_numeric(churn['TotalCharges'], errors='coerce')

churn

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,0,0,1,0,0,DSL,0,0,0,0,0,0,Month-to-month,0,Electronic check,29.85,29.85,0
1,1,0,0,0,34,0,0,DSL,0,0,0,0,0,0,One year,0,Mailed check,56.95,1889.50,0
2,1,0,0,0,2,0,0,DSL,0,0,0,0,0,0,Month-to-month,0,Mailed check,53.85,108.15,0
3,1,0,0,0,45,0,0,DSL,0,0,0,0,0,0,One year,0,Bank transfer (automatic),42.30,1840.75,0
4,0,0,0,0,2,0,0,Fiber optic,0,0,0,0,0,0,Month-to-month,0,Electronic check,70.70,151.65,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,0,0,24,0,0,DSL,0,0,0,0,0,0,One year,0,Mailed check,84.80,1990.50,0
7039,0,0,0,0,72,0,0,Fiber optic,0,0,0,0,0,0,One year,0,Credit card (automatic),103.20,7362.90,0
7040,0,0,0,0,11,0,0,DSL,0,0,0,0,0,0,Month-to-month,0,Electronic check,29.60,346.45,0
7041,1,1,0,0,4,0,0,Fiber optic,0,0,0,0,0,0,Month-to-month,0,Mailed check,74.40,306.60,0
7042,1,0,0,0,66,0,0,Fiber optic,0,0,0,0,0,0,Two year,0,Bank transfer (automatic),105.65,6844.50,0

In [129]:
churn.isna().mean()

gender              0.000000
SeniorCitizen       0.000000
Partner             0.000000
Dependents          0.000000
tenure              0.000000
PhoneService        0.000000
MultipleLines       0.000000
InternetService     0.000000
OnlineSecurity      0.000000
OnlineBackup        0.000000
DeviceProtection    0.000000
TechSupport         0.000000
StreamingTV         0.000000
StreamingMovies     0.000000
Contract            0.000000
PaperlessBilling    0.000000
PaymentMethod       0.000000
MonthlyCharges      0.000000
TotalCharges        0.001562
Churn               0.000000
dtype: float64

In [130]:
churn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   int64
 1   SeniorCitizen     7043 non-null   int64
 2   Partner           7043 non-null   int32
 3   Dependents        7043 non-null   int32
 4   tenure            7043 non-null   int64
 5   PhoneService      7043 non-null   int32
 6   MultipleLines     7043 non-null   int32
 7   InternetService   7043 non-null   object
 8   OnlineSecurity    7043 non-null   int32
 9   OnlineBackup      7043 non-null   int32
 10  DeviceProtection  7043 non-null   int32
 11  TechSupport       7043 non-null   int32
 12  StreamingTV       7043 non-null   int32
 13  StreamingMovies   7043 non-null   int32
 14  Contract          7043 non-null   object
 15  PaperlessBilling  7043 non-null   int32
 16  PaymentMethod     7043 non-null   object
 17  MonthlyCharges    7043 non-null   float64
 18  TotalCharges      7032 non-null   float64
 19  Churn             7043 non-null   int32
dtypes: float64(2), int32(12), int64(3), object(3)
memory usage: 770.5+ KB

In [133]:
churn = pd.get_dummies(churn)
churn

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,InternetService_DSL,InternetService_Fiber optic,InternetService_No,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,0,0,1,0,0,0,0,0,...,1,0,0,1,0,0,0,0,1,0
1,1,0,0,0,34,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,1
2,1,0,0,0,2,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,1
3,1,0,0,0,45,0,0,0,0,0,...,1,0,0,0,1,0,1,0,0,0
4,0,0,0,0,2,0,0,0,0,0,...,0,1,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,0,0,24,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,1
7039,0,0,0,0,72,0,0,0,0,0,...,0,1,0,0,1,0,0,1,0,0
7040,0,0,0,0,11,0,0,0,0,0,...,1,0,0,1,0,0,0,0,1,0
7041,1,1,0,0,4,0,0,0,0,0,...,0,1,0,1,0,0,0,0,0,1
7042,1,0,0,0,66,0,0,0,0,0,...,0,1,0,0,0,1,1,0,0,0

In [ ]:
churn.Churn.value_counts(normalize=True)